# Generated by Django 3.0.6 on 2020-06-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
