# Generated by Django 3.0.5 on 2020-06-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_thumbnails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnails',
            old_name='image',
            new_name='featured',
        ),
    ]
